import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Steppers from '@/components/Stepper'
import Form from '@/components/Form'
import { useState } from 'react'
import LightModeIcon from '@mui/icons-material/LightMode';
import DarkModeIcon from '@mui/icons-material/DarkMode';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [steperStatus, setSteperStatus] = useState(false);
  const [mode, setMode] = useState('light');
  const [icon, setIcon] = useState(<DarkModeIcon className='w-12 h-12'/>);

  const handleSubmit = (data) => {
    setSteperStatus(true);
  };

  const handleMode = () => {
    setMode(mode === 'light' ? 'dark' : 'light');
    setIcon(mode === 'light' ? <LightModeIcon className='w-12 h-12'/> : <DarkModeIcon className='w-12 h-12'/>);
  }

  let isDark=mode==='dark'?true:false;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`flex justify-center flex-col items-center align-middle p-0 w-full ${isDark ? "bg-[#151B28]" : ""}`}>
        <Navbar mode={mode} />
        <div className='flex items-center align-middle justify-center flex-col lg:w-[50vw] md:w-[80vw] xs:w-[95vw] pb-12 '>
          <Steppers steperStatus={steperStatus} mode={mode}/>
          <Form onSubmit={handleSubmit} mode={mode}/>
        </div>
      </div>
      <div className='font-extrabold fixed right-12 bottom-12 rounded-full cursor-pointer' onClick={handleMode}>
        {icon}
      </div>
    </div>
  )
}
